// Netlify Function: /api/upload-url  (mapped via netlify.toml redirect)
// Body: { sessionId, fileName, fileType, fileSize }
// Returns: { uploadUrl, key }
//
// Generates a short-lived, write-only URL that lets the browser upload
// ONE specific file directly to private cloud storage. The URL cannot be
// used to read, list, or overwrite anything else in the bucket, and it
// expires after 10 minutes.

const { S3Client, PutObjectCommand } = require('@aws-sdk/client-s3');
const { getSignedUrl } = require('@aws-sdk/s3-request-presigner');
const crypto = require('crypto');

const s3 = new S3Client({
  region: process.env.S3_REGION || 'auto',
  endpoint: process.env.S3_ENDPOINT,
  credentials: {
    accessKeyId: process.env.S3_ACCESS_KEY_ID,
    secretAccessKey: process.env.S3_SECRET_ACCESS_KEY,
  },
});

// Only allow file types clients would realistically send for tax documents.
// Reject anything else (e.g. executables, scripts) even if the browser lies
// about the type — this is a basic allowlist, not a full content check.
const ALLOWED_TYPES = new Set([
  'application/pdf',
  'image/jpeg',
  'image/png',
  'image/heic',
  'image/heif',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document', // .docx
  'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',      // .xlsx
  'application/vnd.ms-excel',
  'text/csv',
  'application/zip',
]);

const MAX_FILE_SIZE = parseInt(process.env.MAX_FILE_SIZE_BYTES || '27262976', 10); // ~26MB default

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*', // tighten to your domain in production
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
};

function sanitizeFileName(name) {
  return String(name).replace(/[^a-zA-Z0-9._-]/g, '_').slice(0, 150);
}

function json(statusCode, body) {
  return {
    statusCode,
    headers: { ...CORS_HEADERS, 'Content-Type': 'application/json' },
    body: JSON.stringify(body),
  };
}

exports.handler = async (event) => {
  if (event.httpMethod === 'OPTIONS') {
    return { statusCode: 204, headers: CORS_HEADERS, body: '' };
  }
  if (event.httpMethod !== 'POST') {
    return json(405, { error: 'Method not allowed' });
  }

  try {
    const { sessionId, fileName, fileType, fileSize } = JSON.parse(event.body || '{}');

    if (!sessionId || !fileName || !fileType) {
      return json(400, { error: 'sessionId, fileName, and fileType are required' });
    }
    if (!ALLOWED_TYPES.has(fileType)) {
      return json(400, { error: `File type "${fileType}" is not allowed` });
    }
    if (fileSize && Number(fileSize) > MAX_FILE_SIZE) {
      return json(400, { error: 'File is too large' });
    }
    // sessionId should be a UUID generated by the browser per submission —
    // validate the shape so it can't be used to inject arbitrary paths.
    if (!/^[a-f0-9-]{20,60}$/i.test(sessionId)) {
      return json(400, { error: 'Invalid sessionId' });
    }

    const safeName = sanitizeFileName(fileName);
    const key = `uploads/${sessionId}/${crypto.randomUUID()}-${safeName}`;

    const command = new PutObjectCommand({
      Bucket: process.env.S3_BUCKET,
      Key: key,
      ContentType: fileType,
    });

    const uploadUrl = await getSignedUrl(s3, command, { expiresIn: 600 }); // 10 minutes

    return json(200, { uploadUrl, key });
  } catch (err) {
    console.error('upload-url error:', err);
    return json(500, { error: 'Failed to generate upload URL' });
  }
};
